apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: promote
spec:
  params:
  - name: github-secret
    type: string
    description: seret name of the github that has user name, user e-mail and access tolenslack app access token (key is name, email and token respectively)
  - name: from
    type: string
    description: github repository url to be promoted from
  - name: to
    type: string
    description: github repository url to be promoted to
  - name: service
    type: string
    description: service name to be promoted
  steps:
  - name: promote
    image: akihikokuroda/promote
    script: |
      #!/bin/sh
      services promote --from $(params.from) --to $(params.to) --service $(params.service) 
    env:
    - name: COMMIT_NAME
      valueFrom:
        secretKeyRef:
          name: $(params.github-secret)
          key: name
    - name: COMMIT_EMAIL
      valueFrom:
        secretKeyRef:
          name: $(params.github-secret)
          key: email
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.github-secret)
          key: token

